[graph]
# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
all-features = true

[advisories]
version = 2
ignore = []

[bans]
multiple-versions = "allow"
wildcards = 'deny'
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "MPL-2.0",
  "BSD-3-Clause",
  "ISC",
  "Unicode-3.0",
]
exceptions = [
  # Use exceptions for these as they only have a single user
  { allow = ["Zlib"], crate = "tinyvec" },
  { allow = ["OpenSSL"], crate = "ring" },
]
